stages:
  - test
  - deploy

test:
  image: python:3
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test

staging:
  stage: deploy
  image: python:3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev curl
    - gem install dpl
    - dpl --provider=heroku --app=acacia-health-care-staging --api-key=$HEROKU_API_KEY
  only:
    - master

production:
  stage: deploy
  image: python:3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev curl
    - gem install dpl
    - dpl --provider=heroku --app=acacia-health-care --api-key=$HEROKU_API_KEY
  only:
    - master
