stages:
  - test
  - deploy

test:
  image: python:3
  variables:
    DB: $DB
    DB_HOST: $DB_HOST
    DB_PASS: $DB_HOST
    DB_PORT: $DB_PORT
    DB_USER: $DB_USER
    SECRET_KEY: $SECRET_KEY
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test

staging:
  stage: deploy
  image: ubuntu
  variables:
    HEROKU_API_KEY: 278b3638-5715-4040-8f0d-126402c349c5
    DB: $DB
    DB_HOST: $DB_HOST
    DB_PASS: $DB_HOST
    DB_PORT: $DB_PORT
    DB_USER: $DB_USER
    SECRET_KEY: $SECRET_KEY
  before_script:
    - apt-get update -y
    - apt-get install -y ruby-dev git curl node npm
    - npm install -g heroku
    - gem install dpl
  script:
    - dpl --provider=heroku --app=acacia-health-care-staging --api-key=$HEROKU_API_KEY
    - heroku run python manage.py migrate
  only:
    - master

production:
  stage: deploy
  image: ubuntu
  variables:
    HEROKU_API_KEY: 278b3638-5715-4040-8f0d-126402c349c5
    DB: $DB
    DB_HOST: $DB_HOST
    DB_PASS: $DB_HOST
    DB_PORT: $DB_PORT
    DB_USER: $DB_USER
    SECRET_KEY: $SECRET_KEY
  before_script:
    - apt-get update -y
    - apt-get install -y ruby-dev git curl node npm
    - npm install -g heroku
    - gem install dpl
  script:
    - dpl --provider=heroku --app=acacia-health-care --api-key=$HEROKU_API_KEY
    - heroku run python manage.py migrate
  only:
    - master
