stages:
  - test
  - deploy

test:
  image: python:3
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test

staging:
  stage: deploy
  image: ubuntu
  before_script:
    - apt-get update -y
    - DEBIAN_FRONTEND="noninteractive" apt-get install -y curl ruby-dev git nodejs yarn npm
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - gem install dpl
  script:
    - dpl --provider=heroku --app=acacia-health-care-staging --api-key=$HEROKU_API_KEY
    - heroku run python manage.py migrate
  only:
    - master

production:
  stage: deploy
  image: ubuntu
  before_script:
    - apt-get update -y
    - DEBIAN_FRONTEND="noninteractive" apt-get install -y curl ruby-dev git nodejs yarn npm
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - gem install dpl
  script:
    - dpl --provider=heroku --app=acacia-health-care --api-key=$HEROKU_API_KEY
    - heroku run python manage.py migrate
  only:
    - master
