version: "3.7"

services:
    api:
        build: .
        restart: always
        volumes:
            - ./:/usr/share/app:z
        ports:
            - 80:80
        command: python manage.py runserver 0.0.0.0:80
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: runner
            PYTHONUNBUFFERED: 1
            DB_PASS: pass
            DB: nice_marmot
            DB_PORT: '5432'
            SECRET_KEY: fj2l4jl2j4l324jl34
            HOST: localhost
            CLIENT_DOMAIN: localhost
            DEBUG: 1
            SENDER_EMAIL: teste@teste.com

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: runner
            POSTGRES_DB: nice_marmot
