# Generated by Django 3.1.3 on 2020-11-18 20:41

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201118_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='occupation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CI', 'Cuidadora de idosos'), ('AE', 'Auxiliar de enfermagem'), ('TE', 'Técnico em enfermagem'), ('EM', 'Enfermeiro')], max_length=15, validators=[core.models.ValidateChoices((('CI', 'Cuidadora de idosos'), ('AE', 'Auxiliar de enfermagem'), ('TE', 'Técnico em enfermagem'), ('EM', 'Enfermeiro')))]), size=3),
        ),
    ]
