# Generated by Django 3.1.3 on 2020-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201118_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='about',
            field=models.TextField(max_length=1000, null=True, verbose_name='About text'),
        ),
        migrations.AddField(
            model_name='professional',
            name='avg_price',
            field=models.IntegerField(default=0, verbose_name='Average Price'),
            preserve_default=False,
        ),
    ]
