# Generated by Django 3.1.3 on 2020-11-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201118_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='availability',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
