# Generated by Django 3.1.3 on 2020-11-18 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_professional_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='professional',
            name='avg_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(65)], verbose_name='Average Price'),
        ),
    ]
