# Generated by Django 3.1.3 on 2020-11-19 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(height_field=300, null=True, upload_to='avatars', verbose_name='Avatar', width_field=300),
        ),
        migrations.AddField(
            model_name='user',
            name='born',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
        migrations.AddField(
            model_name='user',
            name='celphone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='availability',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='avg_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(65)], verbose_name='Average Price'),
        ),
    ]
