# Generated by Django 3.1.3 on 2020-11-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201119_0335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('client', 'professional')},
        ),
    ]
