# Generated by Django 3.1.3 on 2020-11-19 05:29

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201119_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='professional',
            name='occupation',
            field=models.CharField(choices=[('CI', 'Cuidadora de idosos'), ('AE', 'Auxiliar de enfermagem'), ('TE', 'Técnico em enfermagem'), ('EM', 'Enfermeiro')], max_length=2, validators=[core.models.ValidateChoices((('CI', 'Cuidadora de idosos'), ('AE', 'Auxiliar de enfermagem'), ('TE', 'Técnico em enfermagem'), ('EM', 'Enfermeiro')))]),
        ),
    ]
