# Generated by Django 3.1.3 on 2020-11-20 00:37

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201119_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='availability',
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('recurrence', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True, validators=[core.models.ValidateChoices((('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')))])),
                ('weekly_recurrence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, validators=[core.models.ValidateChoices((('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')))]), null=True, size=None)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.professional')),
            ],
        ),
    ]
