# Generated by Django 3.1.3 on 2020-11-20 02:16

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201120_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True, validators=[core.models.ValidateChoices((('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')))]),
        ),
        migrations.AlterField(
            model_name='availability',
            name='weekly_recurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, validators=[core.models.ValidateChoices((('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')))]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='professional',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='About text'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='avatars', verbose_name='Avatar', width_field=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='celphone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
