# Generated by Django 3.1.3 on 2020-11-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201120_0539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
