# Generated by Django 3.1.3 on 2020-11-23 12:48

from django.db import migrations

def create_deleted_user(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Professional = apps.get_model('core', 'Professional')
    deleted_user = User(
        full_name='Deleted User',
        email='deleted@user.com',
        is_active=False,
    )
    deleted_user.save()
    deleted_professional = Professional(
        user=deleted_user,
        about='Deleted Professional'
    )
    deleted_professional.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_rating'),
    ]

    operations = [
        migrations.RunPython(create_deleted_user)
    ]
