# Generated by Django 3.1.3 on 2020-11-24 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celphone_ddd',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_ddd',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}$')]),
        ),
    ]
