# Generated by Django 3.1.3 on 2020-11-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_professional_saved_in_pagarme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='end',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='start',
            new_name='start_datetime',
        ),
    ]
