# Generated by Django 3.1.3 on 2020-11-30 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_availability_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='availability',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
