# Generated by Django 3.1.4 on 2020-12-01 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201130_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
