# Generated by Django 3.1.4 on 2020-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201203_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pagarme_id',
            field=models.IntegerField(null=True),
        ),
    ]
