# Generated by Django 3.1.4 on 2020-12-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201207_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pagarme_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
