# Generated by Django 3.1.4 on 2020-12-09 22:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201209_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[core.models.validate_cpf]),
        ),
    ]
