# Generated by Django 3.1.3 on 2020-11-23 13:13

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201123_1248'),
        ('services', '0010_auto_20201120_2334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0002_auto_20201121_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=models.SET(core.models.User.get_deleted_user), related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.job'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.Professional.get_deleted_professional), related_name='receipts', to='core.professional'),
        ),
    ]
