# Generated by Django 3.1.3 on 2020-11-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20201123_1316'),
        ('financial', '0005_auto_20201123_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='services.job'),
        ),
    ]
