# Generated by Django 3.1.3 on 2020-11-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_payment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
