# Generated by Django 3.1.4 on 2020-12-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_auto_20201124_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pagaerme_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
