# Generated by Django 3.1.4 on 2020-12-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_payment_pagaerme_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pagaerme_id',
            new_name='pagarme_id',
        ),
    ]
