# Generated by Django 3.1.3 on 2020-11-20 05:39

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20201120_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goías'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraíma'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, validators=[core.models.ValidateChoices((('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goías'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraíma'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')))])),
                ('professional_type', models.CharField(choices=[('CI', 'Cuidadora de idosos'), ('AE', 'Auxiliar de enfermagem'), ('TE', 'Técnico em enfermagem'), ('EM', 'Enfermeiro')], max_length=2, validators=[core.models.ValidateChoices((('CI', 'Cuidadora de idosos'), ('AE', 'Auxiliar de enfermagem'), ('TE', 'Técnico em enfermagem'), ('EM', 'Enfermeiro')))])),
                ('service_type', models.CharField(choices=[('AC', 'Hospital Escort'), ('AD', 'Home Escort'), ('CV', 'Dressings / Vaccines'), ('HC', 'Home Care')], max_length=2, validators=[core.models.ValidateChoices((('AC', 'Hospital Escort'), ('AD', 'Home Escort'), ('CV', 'Dressings / Vaccines'), ('HC', 'Home Care')))])),
                ('start', models.DateTimeField(validators=[services.models.future_validator])),
                ('end', models.DateTimeField(validators=[services.models.future_validator])),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(65)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.professional')),
            ],
        ),
    ]
