# Generated by Django 3.1.3 on 2020-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
