# Generated by Django 3.1.3 on 2020-11-20 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20201120_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(65)]),
        ),
    ]
