# Generated by Django 3.1.3 on 2020-11-20 23:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_delete_rating'),
        ('services', '0008_auto_20201120_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='professional',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.professional'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='services.job')),
            ],
            options={
                'unique_together': {('client', 'job')},
            },
        ),
    ]
