# Generated by Django 3.1.3 on 2020-11-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20201120_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='services.job'),
        ),
    ]
