# Generated by Django 3.1.4 on 2020-12-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20201205_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='services.job'),
        ),
    ]
