# Generated by Django 3.1.3 on 2020-11-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20201123_1316'),
        ('chat', '0003_auto_20201119_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='services.job'),
            preserve_default=False,
        ),
    ]
